services:
  xui:
    image: enwaiax/x-ui
    container_name: x-ui
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    ports:
      #- 54321:54321
      - 54322:54322
      - "54322:54322/udp"
      - 54323:54323
      - "54323:54323/udp"
    restart: always
    networks:
      - net
      - nginx_net
networks:
    net:
    nginx_net:
      external:  true
